import SimonDCP.Arithmetic.LemmaOneFiniteSupportPrototype
import SimonDCP.Arithmetic.LemmaThreeStepSixCarry
import SimonDCP.Arithmetic.LemmaThreeStepSixBitBridge
import SimonDCP.Arithmetic.SampleRecursion
import SimonDCP.Arithmetic.SwapFiber
import SimonDCP.Arithmetic.SwapFiberRepair
import SimonDCP.Arithmetic.TranslationFiber
import SimonDCP.Probability.AffineResidueCounting
import SimonDCP.Probability.ActualStepFourBorn
import SimonDCP.Probability.BoundedTail
import SimonDCP.Probability.BooleanMaskBridge
import SimonDCP.Probability.Conditioning
import SimonDCP.Probability.ConditionalLinearForms
import SimonDCP.Probability.CoordinateSubcubeBorn
import SimonDCP.Probability.CoordinateSubcubeConditionalFamily
import SimonDCP.Probability.CoordinateSubcubeConditionalInjectivity
import SimonDCP.Probability.CoordinateSubcubeParameters
import SimonDCP.Probability.CoordinateSubcubeProjection
import SimonDCP.Probability.CoordinateSubcubeSupport
import SimonDCP.Probability.FaultCountMarkov
import SimonDCP.Probability.FaultPatternSupportBridge
import SimonDCP.Probability.FaultyHighBitCarry
import SimonDCP.Probability.FaultySamplePhase
import SimonDCP.Probability.FiniteConditioningMass
import SimonDCP.Probability.GroupUnionFamily
import SimonDCP.Probability.LabelledBornProbability
import SimonDCP.Probability.LabelledBornPairwiseTail
import SimonDCP.Probability.LabelledParseval
import SimonDCP.Probability.Lemma4AdaptiveWalshEnergy
import SimonDCP.Probability.Lemma4AdaptiveWalshFibre
import SimonDCP.Probability.Lemma4AdaptiveWalshFibreObstruction
import SimonDCP.Probability.Lemma4AdaptiveWalshNormalizedFibre
import SimonDCP.Probability.Lemma4AverageDecoder
import SimonDCP.Probability.Lemma4Decoder
import SimonDCP.Probability.Lemma4PaperDecoder
import SimonDCP.Probability.Lemma4Parameters
import SimonDCP.Probability.Lemma4Repair
import SimonDCP.Probability.Lemma4StepSevenAverage
import SimonDCP.Probability.LemmaOneChebyshevParameters
import SimonDCP.Probability.LemmaOneExactParameters
import SimonDCP.Probability.LemmaOneFaultEnvironmentAveraging
import SimonDCP.Probability.LemmaOneFiniteModel
import SimonDCP.Probability.LemmaOneFixedEnvironment
import SimonDCP.Probability.LemmaOneGoodEnvironment
import SimonDCP.Probability.LemmaOneOuterAveraging
import SimonDCP.Probability.LemmaOneRoundedParameters
import SimonDCP.Probability.LemmaOneRoundedFixedEnvironment
import SimonDCP.Probability.LemmaOneRepaired
import SimonDCP.Probability.LemmaThreeAdaptiveSectorCounterexample
import SimonDCP.Probability.LemmaThreeAdaptiveFibreUpperBound
import SimonDCP.Probability.LemmaThreeBornBounds
import SimonDCP.Probability.LemmaThreeBooleanFinePathUpperBound
import SimonDCP.Probability.LemmaThreeBudgetedFirstClause
import SimonDCP.Probability.LemmaThreeCoherentFibreObstruction
import SimonDCP.Probability.LemmaThreeConservativeThresholdImpact
import SimonDCP.Probability.LemmaThreeCountEnergy
import SimonDCP.Probability.LemmaThreeFiniteRepair
import SimonDCP.Probability.LemmaThreeFirstZeroFrame
import SimonDCP.Probability.LemmaThreePaperFirstClause
import SimonDCP.Probability.LemmaThreePaperPathBridge
import SimonDCP.Probability.LemmaThreePaperPathEnergy
import SimonDCP.Probability.LemmaThreePathRefinement
import SimonDCP.Probability.LemmaThreePostselection
import SimonDCP.Probability.LemmaThreePostselectionSlack
import SimonDCP.Probability.LemmaThreeSectorRefinement
import SimonDCP.Probability.LemmaThreeStepSixAcceptance
import SimonDCP.Probability.LemmaThreeStepSevenRegrouping
import SimonDCP.Probability.LemmaThreeTranscriptModel
import SimonDCP.Probability.LemmaThreeToFourL2
import SimonDCP.Probability.LemmaThreeUniformWalshPaths
import SimonDCP.Probability.LinearPhaseIndependence
import SimonDCP.Probability.OneTimePadCounting
import SimonDCP.Probability.PairwiseBernoulliTail
import SimonDCP.Probability.ProjectionInjectivity
import SimonDCP.Probability.RandomFixedBitsMixture
import SimonDCP.Probability.RectangularGroupPartition
import SimonDCP.Probability.ResidueConditioningAssembly
import SimonDCP.Probability.ResidueConditioningBound
import SimonDCP.Probability.RestrictedParseval
import SimonDCP.Probability.SimultaneousLocalInjectivity
import SimonDCP.Probability.StepFourLabelPhaseBridge
import SimonDCP.Probability.StepTwoJointKernel
import SimonDCP.Probability.StepTwoMeasurementBridge
import SimonDCP.Probability.StepTwoUniformMarginals
import SimonDCP.Probability.TernaryProjectionBridge
import SimonDCP.Probability.TernarySubsetSumBound
import SimonDCP.Quantum.AmplitudeCancellation
import SimonDCP.Quantum.ApproximateReadout
import SimonDCP.Quantum.BitReadout
import SimonDCP.Quantum.ConditionalReadout
import SimonDCP.Quantum.FaultyBasisSample
import SimonDCP.Quantum.FaultPatternFourierProduct
import SimonDCP.Quantum.FaultPatternProductAmplitude
import SimonDCP.Quantum.FourierShift
import SimonDCP.Quantum.IdealCosetSample
import SimonDCP.Quantum.MixedFaultPatternFourierProduct
import SimonDCP.Quantum.PhaseCorrelation
import SimonDCP.Quantum.PhaseTransfer
import SimonDCP.Quantum.Step2Phase

/-!
# Kernel trust audit

The declarations below are the principal machine-checked outputs of the current
formalization. These commands make their axiom dependencies visible during a
build.  Analytic results should expose only standard Lean dependencies.  The
finite exhaustive searches intentionally use `native_decide`, whose generated
evaluation certificates are also printed here.  No result may depend on
`sorryAx` or a user-declared mathematical axiom.
-/

open SimonDCP.Arithmetic.LemmaOneFiniteSupportPrototype
open SimonDCP.Arithmetic.LemmaThreeStepSixCarry
open SimonDCP.Arithmetic.LemmaThreeStepSixBitBridge
open SimonDCP.Arithmetic.SampleRecursion
open SimonDCP.Arithmetic.SwapFiber
open SimonDCP.Arithmetic.SwapFiberRepair
open SimonDCP.Arithmetic.TranslationFiber
open SimonDCP.Probability.AffineResidueCounting
open SimonDCP.Probability.ActualStepFourBorn
open SimonDCP.Probability.BoundedTail
open SimonDCP.Probability.BooleanMaskBridge
open SimonDCP.Probability.Conditioning
open SimonDCP.Probability.ConditionalLinearForms
open SimonDCP.Probability.CoordinateSubcubeBorn
open SimonDCP.Probability.CoordinateSubcubeConditionalFamily
open SimonDCP.Probability.CoordinateSubcubeConditionalInjectivity
open SimonDCP.Probability.CoordinateSubcubeParameters
open SimonDCP.Probability.CoordinateSubcubeProjection
open SimonDCP.Probability.CoordinateSubcubeSupport
open SimonDCP.Probability.FaultCountMarkov
open SimonDCP.Probability.FaultPatternSupportBridge
open SimonDCP.Probability.FaultyHighBitCarry
open SimonDCP.Probability.FaultySamplePhase
open SimonDCP.Probability.FiniteConditioningMass
open SimonDCP.Probability.GroupUnionFamily
open SimonDCP.Probability.LabelledBornProbability
open SimonDCP.Probability.LabelledBornPairwiseTail
open SimonDCP.Probability.LabelledParseval
open SimonDCP.Probability.Lemma4AdaptiveWalshEnergy
open SimonDCP.Probability.Lemma4AdaptiveWalshFibre
open SimonDCP.Probability.Lemma4AdaptiveWalshFibreObstruction
open SimonDCP.Probability.Lemma4AdaptiveWalshNormalizedFibre
open SimonDCP.Probability.Lemma4AverageDecoder
open SimonDCP.Probability.Lemma4Decoder
open SimonDCP.Probability.Lemma4PaperDecoder
open SimonDCP.Probability.Lemma4Parameters
open SimonDCP.Probability.Lemma4Repair
open SimonDCP.Probability.Lemma4StepSevenAverage
open SimonDCP.Probability.LemmaOneChebyshevParameters
open SimonDCP.Probability.LemmaOneExactParameters
open SimonDCP.Probability.LemmaOneFaultEnvironmentAveraging
open SimonDCP.Probability.LemmaOneFiniteModel
open SimonDCP.Probability.LemmaOneFixedEnvironment
open SimonDCP.Probability.LemmaOneGoodEnvironment
open SimonDCP.Probability.LemmaOneOuterAveraging
open SimonDCP.Probability.LemmaOneRoundedParameters
open SimonDCP.Probability.LemmaOneRoundedFixedEnvironment
open SimonDCP.Probability.LemmaOneRepaired
open SimonDCP.Probability.LemmaThreeAdaptiveSectorCounterexample
open SimonDCP.Probability.LemmaThreeAdaptiveFibreUpperBound
open SimonDCP.Probability.LemmaThreeBornBounds
open SimonDCP.Probability.LemmaThreeBooleanFinePathUpperBound
open SimonDCP.Probability.LemmaThreeBudgetedFirstClause
open SimonDCP.Probability.LemmaThreeCoherentFibreObstruction
open SimonDCP.Probability.LemmaThreeConservativeThresholdImpact
open SimonDCP.Probability.LemmaThreeCountEnergy
open SimonDCP.Probability.LemmaThreeFiniteRepair
open SimonDCP.Probability.LemmaThreeFirstZeroFrame
open SimonDCP.Probability.LemmaThreePaperFirstClause
open SimonDCP.Probability.LemmaThreePaperPathBridge
open SimonDCP.Probability.LemmaThreePaperPathEnergy
open SimonDCP.Probability.LemmaThreePathRefinement
open SimonDCP.Probability.LemmaThreePostselection
open SimonDCP.Probability.LemmaThreePostselectionSlack
open SimonDCP.Probability.LemmaThreeSectorRefinement
open SimonDCP.Probability.LemmaThreeStepSixAcceptance
open SimonDCP.Probability.LemmaThreeStepSevenRegrouping
open SimonDCP.Probability.LemmaThreeTranscriptModel
open SimonDCP.Probability.LemmaThreeToFourL2
open SimonDCP.Probability.LemmaThreeUniformWalshPaths
open SimonDCP.Probability.LinearPhaseIndependence
open SimonDCP.Probability.OneTimePadCounting
open SimonDCP.Probability.PairwiseBernoulliTail
open SimonDCP.Probability.ProjectionInjectivity
open SimonDCP.Probability.RandomFixedBitsMixture
open SimonDCP.Probability.RectangularGroupPartition
open SimonDCP.Probability.ResidueConditioningAssembly
open SimonDCP.Probability.ResidueConditioningBound
open SimonDCP.Probability.RestrictedParseval
open SimonDCP.Probability.SimultaneousLocalInjectivity
open SimonDCP.Probability.StepFourLabelPhaseBridge
open SimonDCP.Probability.StepTwoJointKernel
open SimonDCP.Probability.StepTwoMeasurementBridge
open SimonDCP.Probability.StepTwoUniformMarginals
open SimonDCP.Probability.TernaryProjectionBridge
open SimonDCP.Probability.TernarySubsetSumBound
open SimonDCP.Quantum.AmplitudeCancellation
open SimonDCP.Quantum.ApproximateReadout
open SimonDCP.Quantum.BitReadout
open SimonDCP.Quantum.ConditionalReadout
open SimonDCP.Quantum.FaultyBasisSample
open SimonDCP.Quantum.FaultPatternFourierProduct
open SimonDCP.Quantum.FaultPatternProductAmplitude
open SimonDCP.Quantum.FourierShift
open SimonDCP.Quantum.IdealCosetSample
open SimonDCP.Quantum.MixedFaultPatternFourierProduct
open SimonDCP.Quantum.PhaseCorrelation
open SimonDCP.Quantum.PhaseTransfer
open SimonDCP.Quantum.Step2Phase

#print axioms lowPartBitSwap_delta
#print axioms stepSix_topBit_eq_fullSum
#print axioms highBlockTopBit_eq_fullWordTopBit
#print axioms floorLogPaperFlag_false_not_carryVulnerable
#print axioms stepSix_floorLogPaperFlag_false_topBit_eq_fullSum
#print axioms paperGroupCount_mul_log_le_width
#print axioms stepSix_paperGroupCount_floorLogPaperFlag_false_topBit_eq_fullSum
#print axioms ceilRoundedLogLog_counterexample
#print axioms reducedSamplePosition_true_sub_false
#print axioms reducedDot_modEq
#print axioms lemmaOneMap_does_not_preserve_measured_fiber
#print axioms counterexample_preserves_phase_but_not_fiber
#print axioms lemmaOneMap_not_fiberPreserving
#print axioms lemmaOneMap_not_fiberPreserving_on_locallyWellFormed_inputs
#print axioms lowPart_swap_fiber_iff_matching
#print axioms zero_one_scaled_modulus_swap_fiber_iff
#print axioms fullSwap_preserves_contribution
#print axioms permuteCoordinates_preserves_fiber
#print axioms groupContributionLabel_permute_of_preservesGroups
#print axioms allZeroGroupCount_plannedPermute_of_preservesGroups
#print axioms groupContributionLabel_permute_of_relabelsGroups
#print axioms card_allZeroGroups_eq_of_relabelsGroups
#print axioms relabelsGroups_of_summarizedLabel_singleSelection
#print axioms no_fixed_truncatedLabelRelabel_for_partialCrossGroupSwap
#print axioms no_compatible_allZeroCreating_permutation
#print axioms crossGroupPermutationCompatible_iff_movesWholeGroups
#print axioms crossGroupSourceRawWeightForOutput_classification
#print axioms crossGroupSparseBadOutputs_have_zero_raw_weight
#print axioms partialCrossGroupSwap_normalizedWeight
#print axioms crossGroupTruncated_output_counts
#print axioms crossGroupTruncated_no_allZeroGroup_before
#print axioms crossGroupTruncated_has_allZeroGroup_after
#print axioms partialCrossGroupRepair_not_preserves_truncatedInterference
#print axioms certifiedRepair_injective
#print axioms no_certificate_with_partialCrossGroupRepair
#print axioms plannedMeasuredOutcome_bijective
#print axioms certifiedMeasuredRepair_injective
#print axioms certificate_plan_relabelsGroups_of_nonzero_samples
#print axioms certificate_card_allZeroGroups_eq_of_nonzero_samples
#print axioms certificate_card_allZeroGroups_eq_of_distinguishing_summary
#print axioms bad_totalOutcomeWeight_le_good_totalOutcomeWeight
#print axioms fiberCoefficient_translate_fixedXor
#print axioms walshPhase_eq_of_eq_off_zero_set
#print axioms coordinate_independence_destroyed_by_conditioning
#print axioms binaryJointFiberCountsEqual_iff_conditionalDualMasks
#print axioms correlated_overflow_can_destroy_balance
#print axioms nonzero_dot_balanced
#print axioms distinct_nonzero_joint_fiber_card_eq
#print axioms countSmallBranchMass_le_paperThreshold
#print axioms largeNormalizedComponentMass_le_paperThreshold
#print axioms largeNormalizedComponentMass_le_bucketThreshold
#print axioms totalIncoherentPathEnergy_eq
#print axioms pathModel_smallBranchMass_le_paperThreshold
#print axioms compatiblePaths_allBranchesSmall_mass_le
#print axioms uniformWalshPaths_smallBranchMass_le
#print axioms adaptiveSectorTail_le_energyBudget
#print axioms exactSectorMass_le_of_dyadicBudget
#print axioms bucketSectorMass_le_of_quadraticBudget
#print axioms normalizedCoarseMass_sum
#print axioms normalizedAdaptiveSectorEnergy_sum
#print axioms adaptiveSectorEnergy_strictly_exceeds_one
#print axioms totalSectorEnergy_adaptiveBucket_le
#print axioms adaptiveBucketTail_le_of_fineCard
#print axioms card_booleanFinePath
#print axioms booleanFinePath_adaptiveBucketTail_le
#print axioms twelveBooleanBlocks_adaptiveBucketTail_le
#print axioms card_mul_sum_sq_fibreCard_ge
#print axioms equalAmplitudeFibreEnergy_lower_bound
#print axioms powTwo_cleared_collision_lower_bound
#print axioms conservativeTotalDeviationExponent_eq
#print axioms conservativeTotalDeviationExponent_nonneg
#print axioms countErrorEnergy_centering_identity
#print axioms countErrorEnergy_bucketCount_actualMean
#print axioms expected_selectedCountErrorEnergy_actualMean_eq
#print axioms twoBitHash_jointFiber_card_eq_one
#print axioms equalBitCondition_countErrorEnergy_eq_two
#print axioms card_adaptiveFirstZeroRefinements_le_choose
#print axioms twoPowBlock_mul_adaptiveFirstZeroFrameWeight_le_choose
#print axioms finiteConditionalBadMass_le_dyadic
#print axioms finiteConditionalBadMass_le_inverseSquare
#print axioms repairedUniformWalshJointBounds
#print axioms repairedDyadicJointBounds_of_budget
#print axioms repairedConditionalBounds
#print axioms hiddenBit_xor_branch_eq_hPrime
#print axioms paperDirectBranchAmplitude_eq_paperBranchAmplitude
#print axioms paperDirectBranchAmplitude_eq_tPlus_sub_tMinus
#print axioms paperBranchAmplitude_eq_tPlus_sub_tMinus
#print axioms normSq_paperBranchAmplitude
#print axioms paperHiddenAndD_injective
#print axioms sum_normSq_paperCommonPathAmplitude_le_inv_card_low
#print axioms paperPaths_allBranchesSmall_mass_le
#print axioms finiteConditionalBadMass_le_of_splitExponent
#print axioms finiteConditionalBadMass_le_halfExponent
#print axioms paperFirstClause_conditional_small_mass_le_halfExponent
#print axioms branchEnergy_badMass_le_budget
#print axioms paperPaths_allBranchesSmall_mass_le_inv_card_low
#print axioms paperPaths_conditional_allBranchesSmall_mass_le
#print axioms normSq_sum_real_mul_le
#print axioms weightedAmplitude_error_normSq_le_budget
#print axioms coefficientEnergy_restrictedWalshCoefficient_eq
#print axioms weightedAmplitude_restrictedWalsh_error_normSq_le
#print axioms directDoubleSum_eq_weightedAmplitude
#print axioms scaledDirect_sub_scaledMean_normSq_le_budget
#print axioms coefficientEnergy_bResidueCoefficient_eq_collisionSum
#print axioms card_bPaths_le_card_residue_mul_fiberCardBound
#print axioms card_sq_div_le_sum_sq_bResidueFiberCard
#print axioms coefficientEnergy_bResidueCoefficient_const
#print axioms coefficientEnergy_bResidueCoefficient_const_lower_bound
#print axioms coefficientEnergy_bResidueCoefficient_le_fiberCard_mul_sum_normSq
#print axioms coefficientEnergy_bResidueCoefficient_le_card_mul_sum_normSq
#print axioms allZeroHadamardMass_eq
#print axioms diagonalInputMass_destructiveBoolAmplitude
#print axioms allZeroHadamardMass_destructiveBoolAmplitude_eq_zero
#print axioms average_allZeroHadamardMass_environmentAmplitude_eq_half
#print axioms retained_joint_allZeroMass_lt_half_retainedMass
#print axioms sum_normSq_boolHadamardAmplitude
#print axioms restricted_character_orthogonality
#print axioms restricted_parseval
#print axioms card_masksVanishingOn
#print axioms restricted_squaredAmplitude_sum_ge_diagonal_pow
#print axioms labelled_restricted_parseval
#print axioms labelled_restricted_sum_ge_diagonal_pow
#print axioms pow_le_labelledZeroEventMass
#print axioms labelledZeroEventMass_empty_eq_one
#print axioms subsetSumInjectiveOn_of_injectiveWithin
#print axioms labelled_restricted_parseval_eq_diagonal
#print axioms residueFibre_restricted_parseval_eq_diagonal
#print axioms upperTailMass_ge_of_mean_ge_of_threshold_lt_mu
#print axioms rational_upperTailMass_ge_scaled_parameters
#print axioms rational_bayes_residue_bound
#print axioms rational_bayes_residue_bound_of_dyadic
#print axioms completedSelectedSum_translate
#print axioms outsideResidueFibreEquiv
#print axioms card_mul_badResidueCount_le_regular_exceptional
#print axioms card_mul_fullSampleResidueCount_eq
#print axioms joint_mass_le_of_count_bound
#print axioms marginal_mass_eq_of_count_identity
#print axioms card_inside_mul_card_outside_eq
#print axioms normalizedBadResidueMass_le
#print axioms normalizedFullSampleResidueMass_eq
#print axioms normalizedConditionalBadResidueMass_le
#print axioms card_ternaryRelationSamples_le
#print axioms uniform_ternaryCollisionSamples_le
#print axioms uniform_localNonInjectiveSamples_le
#print axioms exceptionalSelectionMass_coordinateSubcube_le
#print axioms fullSubsetSum_eq_free_add_fixed
#print axioms character_fullSubsetSum_eq_free_mul_fixed
#print axioms highBit_sub_eq_residueCarryBit_xor_highBit
#print axioms stdAddChar_halfTurn
#print axioms mixedProductSecretPhase_eq_positionSecretCharacter_freeSelectedSum
#print axioms mixedProductSecretPhase_eq_paperLabelPhase
#print axioms image_boolCoordinateSubcubeResidueFibre_eq_mask
#print axioms projectionInjective_maskCoordinateSubcubeResidueFibre
#print axioms labelledZeroEventMass_maskCoordinateSubcubeResidueFibre_eq
#print axioms labelledZeroEventMass_disjoint_union_eq_mul
#print axioms mass_simultaneousLocalFailure_le_card_mul
#print axioms rank_sub_le_card_sdiff
#print axioms normalizedConditionalBadResidueMass_coordinateSubcube_le_dyadic
#print axioms priorBadMass_badInsideSamples_le
#print axioms normalizedConditionalBadResidueMass_badInsideSamples_le_dyadic
#print axioms mass_simultaneousConditionalFailure_le_sum_dyadic
#print axioms mass_simultaneousConditionalFailure_le_card_mul_dyadic
#print axioms sum_labelledBornWeight_eq_one
#print axioms groupZeroIndicator_pair_mean_eq
#print axioms chebyshev_groupZeroIndicator_le_mean
#print axioms lowerTailMass_groupZeroIndicator_le_paper_bound
#print axioms finite_markov
#print axioms rational_faultTailMass_le_of_coordinate_marginals
#print axioms card_freeCoordinates
#print axioms half_le_card_freeCoordinates_of_faultCount_le_half
#print axioms lowerTailMass_le_mean_div_gap_sq
#print axioms lowerTailMass_le_paper_bound
#print axioms exactMean_of_powerOfTwo_and_exactPartition
#print axioms environmentAveragedFailureMass_le
#print axioms mixedFaultEnvironmentLowerTailMass_rectangular_le
#print axioms mixedFaultEnvironmentLowerTailMass_rectangular_le_half
#print axioms rectangularCollisionBound_zmod_le_quarter
#print axioms paperTailBound_le_quarter
#print axioms nested_lowerTailMass_rectangular_le
#print axioms nested_lowerTailMass_rectangular_exactParameters_le
#print axioms nested_lowerTailMass_rectangular_exactParameters_le_half
#print axioms mixedStepFourBornWeight_eq_fixedEnvironmentWeight_cast
#print axioms mixedStepFourRawOutputMass_div_total_eq_fixedEnvironmentWeight_cast
#print axioms sum_mixedStepFourBornWeight_eq_one_of_stepTwoWeight_ne_zero
#print axioms mixedFixedEnvironmentLowerTailMass_eq_cast_nestedFiniteMass
#print axioms lowerTailMass_fixedEnvironment_rectangular_le
#print axioms mixedFixedEnvironmentLowerTailMass_rectangular_le
#print axioms lowerTailMass_fixedEnvironment_rectangular_le_half
#print axioms mixedFixedEnvironmentLowerTailMass_rectangular_le_half
#print axioms mass_lemmaOneBadEnvironment_le
#print axioms subsetSumInjectiveWithin_mono
#print axioms nestedFiniteMass_le_bad_add
#print axioms nestedFiniteMass_le_of_goodLocalInjectivity
#print axioms mean_div_gap_sq_antitone
#print axioms lowerTailMass_le_paper_bound_of_mean_ge
#print axioms roundedMean_ge_reference
#print axioms roundedCollisionBudget_of_clogBudget
#print axioms paperConstants_clogBudget
#print axioms paperConstants_tailBudget
#print axioms paperConstants_roundedBudgets
#print axioms nested_lowerTailMass_rectangular_lowerMean_le
#print axioms mixedFixedEnvironmentLowerTailMass_rounded_le
#print axioms mixedFixedEnvironmentLowerTailMass_rounded_le_half
#print axioms mixedFixedEnvironmentLowerTailMass_paperConstants_le_half
#print axioms mixedFaultEnvironmentLowerTailMass_rounded_le_half
#print axioms mixedFaultEnvironmentLowerTailMass_paperConstants_le_half
#print axioms repairedLemmaOneSuccessEvent_iff_not_lowerTail
#print axioms mixedFixedEnvironmentSuccessMass_add_lowerTailMass_eq_one
#print axioms mixedFixedEnvironmentSuccessMass_paperConstants_ge_half
#print axioms mixedFaultEnvironmentSuccessMass_add_lowerTailMass_eq_one
#print axioms mixedFaultEnvironmentSuccessMass_paperConstants_ge_half
#print axioms card_groupUnionFamily_le
#print axioms mass_groupUnionFailure_le
#print axioms card_rectangularGroups
#print axioms rectangularGroups_pairwiseDisjoint
#print axioms mass_rectangularGroupUnionFailure_le
#print axioms splitAssignmentPointMass_eq_uniform
#print axioms splitAssignmentEventMass_eq_uniform
#print axioms conditionalEventMass_independent_of_environment
#print axioms lowBitsHom_val
#print axioms image_boolStepTwoMeasuredFibre_eq_maskCoordinateSubcubeResidueFibre
#print axioms labelledZeroEventMass_stepTwoMeasuredFibre_eq
#print axioms finiteMass_uniform_preimage_eq
#print axioms hasUniformLocalMarginals_lowBits
#print axioms hasUniformLocalMarginals_prod_of_first_marginal
#print axioms phasedLabelledSquaredAmplitude_eq
#print axioms phasedLabelledBornWeight_paperStepFour_eq
#print axioms phasedLabelledZeroEventMass_paperStepFour_coordinateSubcube_eq
#print axioms mixedPostPositionDftProductAmplitude_eq_base_mul_secretPhase_of_mem
#print axioms mixedStepFourFibreWalshAmplitude_eq_paperPhased
#print axioms mixedStepFourRawOutputMass_eq_common_normSq_mul
#print axioms mixedStepFourRawTotalMass_eq_common_normSq_mul_denominator
#print axioms mixedStepFourRawOutputMass_div_total_eq_bornWeight
#print axioms mixedStepFourBornWeight_eq_labelled
#print axioms mixedStepFourZeroEventMass_coordinateGroup_eq
#print axioms mixedStepFourZeroEventMass_disjoint_union_eq_mul
#print axioms sum_stepTwoJointWeight_eq_one
#print axioms hasUniformLocalMarginals_stepTwoJointWeight_lowBits
#print axioms cast_stepTwoJointWeight_eq_sum_fibre_mixedBorn
#print axioms mean_indicatorSum_ge
#print axioms variance_indicatorSum
#print axioms finite_chebyshev
#print axioms chebyshev_indicatorSum_le_mean
#print axioms printedBinDeviationExponent_eq_corrected_add_n
#print axioms corrected_c12_rpow_le
#print axioms uniformBinTotal
#print axioms weightedSumErrorBound
#print axioms aggregatePolynomialExponent_c12_three_halves
#print axioms weightedAmplitude_pair_additive
#print axioms relative_error_of_additive_error
#print axioms weightedAmplitude_pair_relative
#print axioms weightedAmplitude_pair_error_normSq_le
#print axioms pairedWeightedAmplitudeMismatchEnergy_le_budget
#print axioms lemmaFour_additive_readout
#print axioms lemmaFour_uniform_counts_readout
#print axioms lemmaFour_labelled_additive_readout
#print axioms lemmaFour_labelled_uniform_counts_readout
#print axioms lemmaFour_state_labelled_additive_readout
#print axioms lemmaFour_state_labelled_uniform_counts_readout
#print axioms labelledPairedCountDeviationBad_mass_le
#print axioms lemmaFour_state_labelled_decoder_failure_mass_le
#print axioms lemmaFour_state_labelled_decoder_success_mass_ge
#print axioms pairCountErrorEnergy_le_two_countErrorEnergy
#print axioms average_state_labelled_decoder_success_ge
#print axioms expectedBranchCountBudget_selected_eq
#print axioms average_state_labelled_decoder_success_ge_of_branch_count_energy
#print axioms average_state_labelled_decoder_success_ge_of_selected_pair_collision
#print axioms equalBitCondition_not_weightedPairCollisionUniform
#print axioms average_decoder_success_ge_of_stepSeven_exact_energy
#print axioms average_decoder_success_ge_of_stepSeven_diagonal_energy
#print axioms average_decoder_success_ge_of_stepSeven_fiber_energy
#print axioms average_decoder_success_ge_of_stepSeven_selected_pair_collision_of_fiber_bound
#print axioms average_decoder_success_ge_of_stepSeven_selected_pair_collision
#print axioms paperPositive_eq_branchSecretPhase_mul_walsh
#print axioms paperSignedBranchCount_eq_targetSign_mul_walshSignedCount
#print axioms paperSignedMismatchEnergy_eq_paperWalshMismatchEnergy
#print axioms pairedMismatchEnergy_scaledPaperBranchAmplitude_eq_walsh
#print axioms paper_decoder_success_ge_of_walsh_mismatch_energy
#print axioms weightedAdaptiveSignedEnergy_eq_diagonal_add_offDiagonal
#print axioms paperWalshSignedBranchCount_true_sub_false_eq_sum_contribution
#print axioms paperWalshMismatchEnergy_eq_sum_pairCorrelation
#print axioms sum_paperWalshPairCorrelation_self_eq_pathEnergy
#print axioms paperWalshMismatchEnergy_eq_pathEnergy_add_offDiagonal
#print axioms paperWalshMismatchEnergy_le_normalizationBound_add_offDiagonal
#print axioms paper_decoder_success_ge_of_adaptive_offDiagonal_bound
#print axioms sum_paperWalshDifferenceContribution_sq_le_fibreCount_sq
#print axioms paperWalshMismatchEnergy_le_sum_weight_mul_fibreCount_sq
#print axioms sum_weight_mul_paperCompatibleHiddenCount_eq_pathEnergy
#print axioms paperWalshMismatchEnergy_le_fibreCard_mul_pathEnergy
#print axioms paperWalshMismatchEnergy_le_card_hidden_mul_pathEnergy
#print axioms paperWalshMismatchEnergy_le_fibreCard_mul_normalizationBound
#print axioms paper_decoder_success_ge_of_compatibleHiddenFibreCard
#print axioms paper_decoder_success_ge_of_completeTranscriptSeparatesHidden
#print axioms sum_normSq_common_mul_paperCompatibleHiddenCount_eq_pathEnergy
#print axioms paperWalshMismatchEnergy_le_normalizedFibreWeight_mul_pathEnergy
#print axioms paperWalshMismatchEnergy_le_normalizedFibreWeight_mul_inv_card_low
#print axioms paper_decoder_success_ge_of_normalizedFibreWeight
#print axioms paper_decoder_success_ge_of_unit_normalizedFibreWeight
#print axioms paper_decoder_success_ge_of_reciprocal_fibre_normalization
#print axioms paperCompatibleHiddenCount_eq_fibreCard
#print axioms sum_paperCompatibleHiddenCount_eq_card_paths
#print axioms card_paths_le_card_transcript_mul_fibreCardBound
#print axioms card_compatibleHiddenBin_le_count
#print axioms mean_le_fibreCardBound_add_error_of_compatibleHiddenBin
#print axioms paperMean_le_fibreCardBound_add_error_of_compatibleHiddenBin
#print axioms half_paperMean_le_fibreCardBound_of_compatibleHiddenBin
#print axioms c12_nineNMean_half_le_fibreCardBound
#print axioms card_paths_sq_div_card_transcript_le_sum_sq_fibreCount
#print axioms powTwo_card_paths_obstruction
#print axioms lemmaFour_decoder_failure_mass_le
#print axioms lemmaFour_decoder_success_mass_ge
#print axioms eventMass_finset_exists_le
#print axioms pairedCountDeviationBad_mass_le
#print axioms repairedLemmaFour_additive_success_mass_ge
#print axioms repairedLemmaFour_relative_success_mass_ge
#print axioms one_term_change_can_escape_any_multiplicative_zero_bound
#print axioms afterPositionDftState_apply_eq_normalizedDft
#print axioms probPositionOutcome_afterPositionDft
#print axioms hadamard_fixedBitState_apply
#print axioms SimonDCP.Quantum.FaultyBasisSample.probOutcome_afterHadamard
#print axioms productSelectionAmplitude_ne_zero_iff
#print axioms sum_normSq_productSelectionAmplitude
#print axioms probOutcome_faultPatternProductState
#print axioms postPositionDftProductAmplitude_ne_zero_iff
#print axioms sum_selection_normSq_postPositionDftProductAmplitude
#print axioms sum_normSq_postPositionDftProductAmplitude
#print axioms mixedPostPositionDftProductAmplitude_eq_surrogate_mul_phase
#print axioms mixedPostPositionDftProductAmplitude_ne_zero_iff
#print axioms sum_selection_normSq_mixedPostPositionDftProductAmplitude
#print axioms SimonDCP.Quantum.BitReadout.probOutcome_encodedBit
#print axioms wrong_probability_eq_mismatch
#print axioms correct_probability_ge_of_mismatch_norm_le
#print axioms pairedCorrectMass_add_pairedWrongMass
#print axioms pairedCorrectMass_ge_of_mismatchEnergy_le
#print axioms pairedCorrectMass_ge_of_sum_mismatch_norm_le
#print axioms probQubit0_hadamardFirst_wrong_eq
#print axioms probQubit0_hadamardFirst_correct_eq
#print axioms probQubit0_hadamardFirst_correct_ge_of_sum_mismatch_norm_le
#print axioms readout_of_exact_balancedRelativePhase
#print axioms dft_twoPoint
#print axioms probOutcome_idealCosetState
#print axioms encodeThroughMeasuredXor_eq_globalPhase
#print axioms phase_factor_lastBit
#print axioms relativeHighBitPhase_of_lastBit_one
